### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/timesheet#115]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] crm_phonecall_timesheet
- [x] crm_timesheet - By @cubells - #126 
- [ ] hr_attendance_analysis
- [ ] hr_timesheet_activity_begin_end
- [ ] hr_timesheet_fulfill
- [ ] hr_timesheet_holidays
- [ ] hr_timesheet_improvement
- [ ] hr_timesheet_print
- [ ] hr_timesheet_reminder
- [ ] hr_timesheet_sheet_change_period
- [x] hr_timesheet_sheet_week_start_day -> hr_timesheet_sheet_week - By @lreficent - #136
- [x] hr_timesheet_task_required - By @benwillig - #120

**Comment by LoisRForgeFlow** [comment]
No need to migrate 'hr_timesheet_sheet_week_start_day', I integrated the feature into 'hr_timesheet_sheet' here: https://github.com/OCA/hr-timesheet/pull/136

**Comment by pedrobaeza** [comment]
Well, you need to migrate it, but as an improvement of the other module :wink: and then you will need to add OpenUpgrade reference for that merging.

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza Done! https://github.com/OCA/OpenUpgrade/pull/1567 :grin:

**Comment by emagdalenaC2i** [comment]
@pedrobaeza You can check hr_timesheet_sheet_week_start_day - To be merged in hr_timesheet_sheet_week - By @lreficent - #136
