### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/timesheet#63]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] hr_timesheet_fulfill
- [ ] hr_timesheet_print
- [ ] hr_timesheet_improvement
- [ ] crm_timesheet
- [ ] hr_timesheet_reminder
- [ ] hr_timesheet_task - By @PierreFaniel - #83 
- [ ] timesheet_task - To be removed
- [ ] hr_timesheet_holidays
- [ ] hr_timesheet_sheet_change_period - By @mikevhe18 - #85 
- [ ] hr_attendance_analysis
- [ ] hr_timesheet_activity_begin_end - By @Martronic-SA - #96

**Comment by sciallo** [comment]
With official modules now missing in the community version (eg hr_timesheet_invoice) is it going to be plausible? am I better off deploying and developing custom modules on version 8 at this point in time as "warned" in [this article](https://stadler-its.de/blog/stadler-its-blog-1/post/odoo-9-an-open-source-and-marketing-nightmare-9)?

**Comment by Martronic-SA** [comment]
Would it be possible to add hr_timesheet_invoice (and sale_contract) part of the hr-timesheet?

**Comment by Martronic-SA** [comment]
Ok, timesheet (hr.analytic.timesheet) has disappeared in favor of pure analytic lines with a is_timasheet flag.
Direct analytic lines invoicing seems to have been replaced by invoicing through sale order with sale/sale_analytic and sale_timesheet modules.
Those modules will look for an existing sale order with the same project (analytic account)  as the analytic line and they will look for an existing order line with same analytic account and product price and add the analytic line quantity to it or create an new order line.
However, sign in / out by project is gone. Should we create a new module for that?
