### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/timesheet#84]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] crm_timesheet - By @chienandalu - #105 
- [ ] hr_attendance_analysis
- [ ] hr_timesheet_activity_begin_end
- [ ] hr_timesheet_fulfill
- [ ] hr_timesheet_holidays in #114 by @aheficent 
- [ ] hr_timesheet_improvement
- [ ] hr_timesheet_print
- [ ] hr_timesheet_reminder
- [ ] hr_timesheet_sheet_change_period - replaced by #123 by @aheficent 
- [ ] hr_timesheet_sheet_week_start_day
- [ ] hr_timesheet_task
- [ ] timesheet_task

**Comment by AaronHForgeFlow** [comment]
I'll propose a PR for hr_timesheet_holidays

**Comment by feketemihai** [comment]
@elicoidal you have the pr in #114
